name: Package VS Code Extension

on:
  push:
    tags:
      - 'v*' # Tagged commits
    branches:
      - '**' # All branches

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install vsce
      run: npm install -g vsce

    - name: Install dependencies
      run: npm install

    - name: Run copy-binaries
      run: npm run copy-binaries

    # Non-tagged commit
    - name: Package (Non-tagged commit)
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: vsce package --version $(git rev-parse --short HEAD)
      
    # Tagged commit
    - name: Package (Tagged commit)
      if: startsWith(github.ref, 'refs/tags/')
      run: vsce package --version ${GITHUB_REF#refs/tags/v}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-extension-vsix
        path: ./*.vsix
