name: Create and Publish Packages

on:
  push:
    tags:
      - 'artifact/**/*'
      - 'publish/**/*'

jobs:
  build-intellij:
    runs-on: ubuntu-latest
    if: contains(github.ref, '/intellij/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install
        npm install -g pkg

    - name: Build pkg
      run: |
        yarn run cli:package
        yarn run cli:copy-binaries
        yarn run prepare-intellij-bins

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
      
    - name: Update Version
      working-directory: ./src/intellij/vidoc
      run: |
        VERSION=${GITHUB_REF##*/}
        echo $VERSION
        sed -i 's/^pluginVersion=.*/pluginVersion='"$VERSION"'/' gradle.properties

    - name: Build and Sign IntelliJ Plugin
      working-directory: ./src/intellij/vidoc
      env:
        INTELLIJ_CERTIFICATE_CHAIN: ${{ secrets.INTELLIJ_CERTIFICATE_CHAIN }}
        INTELLIJ_PRIVATE_KEY: ${{ secrets.INTELLIJ_PRIVATE_KEY }}
        INTELLIJ_PRIVATE_KEY_PASSWORD: ${{ secrets.INTELLIJ_PRIVATE_KEY_PASSWORD }}
      run: |
        chmod +x ./gradlew
        ./gradlew buildPlugin
        ./gradlew signPlugin
        FILENAME=$(ls build/distributions/*.zip | head -n 1)
        cp "$FILENAME" ../../../artifact-intellij.zip


    - name: Upload IntelliJ artifact
      if: startsWith(github.ref, 'refs/tags/artifact/')
      uses: actions/upload-artifact@v2
      with:
        name: artifact-intellij
        path: ./artifact-intellij.zip
      
  build-vscode:
    runs-on: ubuntu-latest
    if: contains(github.ref, '/vscode/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Install VSCE
      run: npm install -g vsce

    - name: Run custom build script
      run: npm run copy-binaries

    - name: Set Version
      run: |
        VERSION=${GITHUB_REF##*/}
        echo "Setting version to: $VERSION"
        jq '.version="'$VERSION'"' package.json > tmp.json && mv tmp.json package.json

    - name: Package extension
      run: |
        yarn run copy-binaries
        vsce package

    - name: Upload VSCode artifact
      if: startsWith(github.ref, 'refs/tags/artifact/')
      uses: actions/upload-artifact@v2
      with:
        name: my-vsix-file
        path: ./*.vsix

    - name: Publish to Visual Studio Marketplace
      if: startsWith(github.ref, 'refs/tags/publish/')
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        preRelease: true
        pat: ${{ secrets.VSCE_PUBLISH_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com
