name: Create VSIX package

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  tags:
    - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run custom build script
      run: npm run copy-binaries

    - name: Set Version (Non-tagged commit)
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: |
        echo "Setting version to: 0.0.1"
        jq '.version="0.0.1"' package.json > tmp.json && mv tmp.json package.json

    - name: Set Version (Tagged commit)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Setting version to: $VERSION"
        jq '.version="'$VERSION'"' package.json > tmp.json && mv tmp.json package.json

    - name: Package extension
      run: vsce package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-vsix-file
        path: ./*.vsix
